### ISSUE TITLE
icu-center

### ISSUE THREAD

**Issue by Neteraxe** [NWUCA/zaobot#11]
组织只有4个人吗?
可否与我们的icu-center整合，或者两边都分流
https://github.com/icu-center

**Comment by Neteraxe** [comment]
这样组织就有7个人了，还有几个常年活跃与GitHub issue区的同学

**Comment by cjc7373** [comment]
你好, 该组织为西大计算机协会的附属组织, 可能无法与贵组织合并.

**Comment by Neteraxe** [comment]
我们也是西大计协组织，是现任会长建立的

**Comment by Neteraxe** [comment]
@cjc7373
